package com.example.ToDoList.dto;

/**
 * Data Transfer Object for creating new Todo items.
 * 
 * <p>
 * This DTO is used when clients send POST requests to create new todos.
 * It only includes fields that should be provided by the client - the ID
 * and timestamps are auto-generated by the system.
 * </p>
 * 
 * <p>
 * Example JSON request body:
 * </p>
 * 
 * <pre>
 * {
 *   "title": "Learn Spring Boot",
 *   "description": "Complete the tutorial"
 * }
 * </pre>
 * 
 * @author Abhay (avidAbhay)
 * @version 1.0
 * @since 1.0
 */
public class CreateTodoRequest {

    /** Title of the new todo (required) */
    private String title;

    /** Detailed description of the new todo (optional) */
    private String description;

    // ==================== Constructors ====================

    /**
     * Default no-argument constructor.
     * Required for JSON deserialization by Jackson.
     */
    public CreateTodoRequest() {
    }

    /**
     * Constructor with all fields.
     * 
     * @param title       the title of the todo
     * @param description the description of the todo
     */
    public CreateTodoRequest(String title, String description) {
        this.title = title;
        this.description = description;
    }

    // ==================== Getters and Setters ====================

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
